In [1]:
import pandas as pd
class DataPrepKit:
    def read_data (self,file_path):
        file_format=file_path.split('.')[-1].lower()
        if file_format =='csv':
            return pd.read_csv(file_path)
        elif file_format in['xls','xlsx']:
            return pd.read_excel(file_path)
        elif file_format=='json':
            return pd.read_json()
        else:
             raise ValueError("Unsupported file format. Please provide a file with a .csv, .xlsx, .xls, or .json extension.")
           
    def data_summary(self,df):
        print("basic information")
        df.info()
        print("summary")
        print(df.describe())
    def handle_missing_values(self, df, value):
        return df.fillna(value)
    
    def categorical_encoding(self,df):
        categorical_cols = df.select_dtypes(include=['object']).columns
        encoded_df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)  
        return encoded_df

In [2]:

          
   #to use class
#data Reading 
data_prep=DataPrepKit()
file_path=input("enter your path")
df= data_prep.read_data(file_path)
df

enter your path C:\Users\alhal\OneDrive\Documents\dataset_olympics.xlsx

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,35656,Stuart Fitzsimmons,M,19.0,NaN,NaN,Great Britain,GBR,1976 Winter,1976,Winter,Innsbruck,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
69996,35656,Stuart Fitzsimmons,M,19.0,NaN,NaN,Great Britain,GBR,1976 Winter,1976,Winter,Innsbruck,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
69997,35657,"David Thomas ""Dave"" Fitzsimons",M,26.0,170.0,65.0,Australia,AUS,1976 Summer,1976,Summer,Montreal,Athletics,"Athletics Men's 10,000 metres",NaN
69998,35657,"David Thomas ""Dave"" Fitzsimons",M,30.0,170.0,65.0,Australia,AUS,1980 Summer,1980,Summer,Moskva,Athletics,"Athletics Men's 5,000 metres",NaN
69999,35658,Marek Fiurek,M,23.0,180.0,68.0,Czech Republic,CZE,1998 Winter,1998,Winter,Nagano,Nordic Combined,Nordic Combined Men's Team,NaN

In [ ]:
#to summarize data
data_prep.data_summary (df)

In [ ]:
# Handle missing values
filled_data = data_prep.handle_missing_values(df, 0)
filled_data

In [ ]:
#  Categorical encoding
encoded_data = data_prep.categorical_encoding(df)
encoded_data